const LogEvent = {
    WEBSOCKET: 'WEBOSCKET',
    SERVER_SENT_EVENT: 'SERVER SENT EVENT',
    API: 'API',
    LOG_MASTER: 'LOG MASTER',
    TRANSACTION_COUNT: 'NO TRANSACTION COUNT',
    LOG_TRANSAKSI: 'LOG TRANSAKSI',
    TRACE: 'TRACE',
    SEQUELIZE_ERROR: 'SEQUELIZE ERROR',
    NON_WHITELISTED_IP: 'NON WHITELISTED IP',
    MONITOR_API: 'MONITOR API',
    MIGRATION: 'MIGRATION',
    GLOBAL_REPORT: 'GLOBAL REPORT',
}

export default LogEvent;